#include "FFIconsts.h"

NvU32 c_NV_SCANOUT_INTENSITY_DATA_VER() { return NV_SCANOUT_INTENSITY_DATA_VER; }
NvU32 c_NV_SCANOUT_WARPING_VER() { return NV_SCANOUT_WARPING_VER; }
NvU32 c_NV_SCANOUT_WARPING_STATE_VER() { return NV_SCANOUT_WARPING_STATE_VER; }
NvU32 c_NV_SCANOUT_INTENSITY_STATE_VER() { return NV_SCANOUT_INTENSITY_STATE_VER; }
NvU32 c_NV_SCANOUT_INFORMATION_VER() { return NV_SCANOUT_INFORMATION_VER; }
NvU32 c_NV_GPU_DISPLAYIDS_VER() { return NV_GPU_DISPLAYIDS_VER; }